package com.heliopales.bladeexpertfiller

const val EXPORTATION_STATE_EMPTY = 0
const val EXPORTATION_STATE_EXPORTED = 1
const val EXPORTATION_STATE_NOT_EXPORTED = 2

const val INDEX_DAMAGE_LOOP_BASE = 0
const val INDEX_DAMAGE_LOOP_POSI = 1
const val INDEX_DAMAGE_LOOP_DEPT = 2
const val INDEX_DAMAGE_LOOP_TYPE = 3
const val INDEX_DAMAGE_LOOP_SEVE = 4

const val PICTURE_TYPE_DAMAGE = 0
const val PICTURE_TYPE_DRAIN = 3
const val PICTURE_TYPE_LPS = 4
const val PICTURE_TYPE_TURBINE = 1
const val PICTURE_TYPE_BLADE = 2